/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contagem;

import javax.swing.DefaultListModel;

/**
 *
 * @author Home
 */
public class Contagem extends javax.swing.JFrame {
    private int from;
    private int to;
    private int step;
    private boolean dadosSeguros;
     
    private void setDadosSeguros(boolean dadosSeguros){
        this.dadosSeguros = dadosSeguros;        
    }
    
    public boolean isDadosSeguros(){
        return dadosSeguros;
    }
    
    public void verificarContagemInfinita(){
        setDadosSeguros(false);
        if(to>from && step>0) setDadosSeguros(true);
        else if(to<from && step<0) setDadosSeguros(true);
    }
    
    /**
     * Creates new form Contagem
     */
    public Contagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sldAte = new javax.swing.JSlider();
        sldPasso = new javax.swing.JSlider();
        sldDe = new javax.swing.JSlider();
        txtDe = new javax.swing.JTextField();
        txtAte = new javax.swing.JTextField();
        txtPasso1 = new javax.swing.JTextField();
        txtPasso2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setBackground(getBackground());
        jLabel1.setFont(new java.awt.Font("Curlz MT", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contador Automático");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Conte de:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("até:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("de");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("em");

        sldAte.setMaximum(1000);
        sldAte.setMinimum(-1000);
        sldAte.setValue(0);
        sldAte.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldAteStateChanged(evt);
            }
        });

        sldPasso.setMinimum(-100);
        sldPasso.setValue(0);
        sldPasso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldPassoStateChanged(evt);
            }
        });

        sldDe.setMaximum(1000);
        sldDe.setMinimum(-1000);
        sldDe.setValue(0);
        sldDe.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldDeStateChanged(evt);
            }
        });

        txtDe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDe.setForeground(new java.awt.Color(204, 0, 0));
        txtDe.setText("0");
        txtDe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDeFocusLost(evt);
            }
        });

        txtAte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAte.setForeground(new java.awt.Color(204, 0, 0));
        txtAte.setText("0");
        txtAte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAteFocusLost(evt);
            }
        });

        txtPasso1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPasso1.setForeground(new java.awt.Color(204, 0, 0));
        txtPasso1.setText("0");
        txtPasso1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasso1FocusLost(evt);
            }
        });

        txtPasso2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPasso2.setForeground(new java.awt.Color(204, 0, 0));
        txtPasso2.setText("0");
        txtPasso2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasso2FocusLost(evt);
            }
        });

        jScrollPane2.setViewportView(lista);

        jButton2.setText("Contar =>>>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAte))
                                    .addComponent(sldAte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sldPasso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(sldDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDe, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPasso1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPasso2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(sldAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(txtPasso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPasso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldPasso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldDeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDeStateChanged
        from = sldDe.getValue();
        txtDe.setText(Integer.toString(from));            
    }//GEN-LAST:event_sldDeStateChanged

    private void sldAteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldAteStateChanged
        to = sldAte.getValue();
        txtAte.setText(Integer.toString(to));
    }//GEN-LAST:event_sldAteStateChanged

    private void sldPassoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldPassoStateChanged
        step = sldPasso.getValue();
        txtPasso1.setText(Integer.toString(step));
        txtPasso2.setText(Integer.toString(step));
    }//GEN-LAST:event_sldPassoStateChanged

    private void txtDeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeFocusLost
        from = Integer.parseInt(txtDe.getText());
        if(from < sldDe.getMinimum()){
            from = sldDe.getMinimum();
            txtDe.setText(Integer.toString(from));
        }
        if(from > sldDe.getMaximum()){
            from = sldDe.getMaximum();
            txtDe.setText(Integer.toString(from));
        }
        sldDe.setValue(from);
    }//GEN-LAST:event_txtDeFocusLost
    
    private void txtAteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAteFocusLost
        to = Integer.parseInt(txtAte.getText());
        if(to < sldAte.getMinimum()){
            to = sldAte.getMinimum();
            txtAte.setText(Integer.toString(to));
        }
        if(to > sldAte.getMaximum()){
            to = sldAte.getMaximum();
            txtAte.setText(Integer.toString(to));
        }
        sldAte.setValue(to);
    }//GEN-LAST:event_txtAteFocusLost

    private void txtPasso1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasso1FocusLost
        step = Integer.parseInt(txtPasso1.getText());
        if(step < sldPasso.getMinimum()){
            step = sldPasso.getMinimum();
        }
        if(step > sldPasso.getMaximum()){
            step = sldPasso.getMaximum();
        }
        sldPasso.setValue(step);
        txtPasso1.setText(Integer.toString(step));
        txtPasso2.setText(Integer.toString(step));
    }//GEN-LAST:event_txtPasso1FocusLost

    private void txtPasso2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasso2FocusLost
        step = Integer.parseInt(txtPasso2.getText());
        if(step < sldPasso.getMinimum()){
            step = sldPasso.getMinimum();
        }
        if(step > sldPasso.getMaximum()){
            step = sldPasso.getMaximum();
        }
        sldPasso.setValue(step);
        txtPasso1.setText(Integer.toString(step));
        txtPasso2.setText(Integer.toString(step));
    }//GEN-LAST:event_txtPasso2FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultListModel list = new DefaultListModel();  
        int i;
        verificarContagemInfinita();
        if(isDadosSeguros()){
            if(step > 0){
                for(i = from; i <= to; i += step)
                    list.addElement(i);                            
            }
            else if(step < 0){
                for(i = from; i >= to; i += step)
                    list.addElement(i);
            }

            lista.setModel(list);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lista;
    private javax.swing.JSlider sldAte;
    private javax.swing.JSlider sldDe;
    private javax.swing.JSlider sldPasso;
    private javax.swing.JTextField txtAte;
    private javax.swing.JTextField txtDe;
    private javax.swing.JTextField txtPasso1;
    private javax.swing.JTextField txtPasso2;
    // End of variables declaration//GEN-END:variables


}
